Fix multilang parser '.mjs' support, __dirname not defined error and update scripts
Leaflet/Leafdoc pull request #53
Opened 2020-07-21 12:36 UTC by mondeja

- `src/parsers/multilang.mjs` I've included a exception when ' .mjs'  files are found by `comment-patterns` library. Also opened [a pull in `comment-patterns`](https://github.com/nknapp/comment-patterns/pull/9) including `.mjs` modules support, but the last change in the project was 2 years ago, so we need to found another way of extract comments or include this type of exceptions to prevent next error happening when I run `npm install`:
```
> leafdoc@1.5.1 update-markdown-leafdoc /home/mondeja/files/code/Leafdoc
> src/cli.mjs -t templates/markdown src/cli.mjs src/leafdoc.mjs --verbose -o Leafdoc.md

/home/mondeja/files/code/Leafdoc/node_modules/comment-patterns/index.js:18
    throw new Error("Cannot find language definition for '" + filename + "'")
          ^

Error: Cannot find language definition for 'src/cli.mjs'
    at langIndex (/home/mondeja/files/code/Leafdoc/node_modules/comment-patterns/index.js:18:11)
    at Function.commentRegex [as regex] (/home/mondeja/files/code/Leafdoc/node_modules/comment-patterns/index.js:50:28)
    at extract (/home/mondeja/files/code/Leafdoc/node_modules/multilang-extract-comments/index.js:31:17)
    at multilangParser (file:///home/mondeja/files/code/Leafdoc/src/parsers/multilang.mjs:8:20)
    at Leafdoc.addStr (file:///home/mondeja/files/code/Leafdoc/src/leafdoc.mjs:228:24)
    at Leafdoc.addBuffer (file:///home/mondeja/files/code/Leafdoc/src/leafdoc.mjs:193:15)
    at Leafdoc.addFile (file:///home/mondeja/files/code/Leafdoc/src/leafdoc.mjs:185:15)
    at file:///home/mondeja/files/code/Leafdoc/src/cli.mjs:57:8
    at Array.forEach (<anonymous>)
    at file:///home/mondeja/files/code/Leafdoc/src/cli.mjs:52:8
```

- `src/template.mjs` `__dirname` global constant have been replaced by path resolution from working directory. This prevents next error running `npm install`:
```
file:///home/mondeja/files/code/Leafdoc/src/template.mjs:10
let templateDir = `${__dirname  }/../templates/basic`;

ReferenceError: __dirname is not defined
```
-  `src/regexps.mjs` A minor fix to prevent this:
```
> leafdoc@1.5.1 update-markdown-leafdoc /home/mondeja/files/code/Leafdoc
> src/cli.mjs -t templates/markdown src/cli.js src/leafdoc.mjs --verbose -o Leafdoc.md

file:///home/mondeja/files/code/Leafdoc/src/regexps.mjs:34
	leafDirective = xRegExp(`  \\s* ${  char  } (?<directive> \\S+ ) (\\s+ (?<content> [^;\\n]+ )){0,1} `, 'gnx');
	              ^

ReferenceError: Cannot access 'leafDirective' before initialization
```

2020-07-21 22:20 UTC, IvanSanchez requested changes

2020-07-21 22:20 UTC, IvanSanchez commented on src/parsers/multilang.mjs
> +	// see https://git.io/JJWUQ
No me pongas URLs acortadas, por favor. La URL completa (`https://github.com/nknapp/comment-patterns/pull/9`) da mucho más contexto aquí.

2020-07-21 22:20 UTC, IvanSanchez commented on src/regexps.mjs
> -	leafDirective = xRegExp(`  \\s* ${  char  } (?<directive> \\S+ ) (\\s+ (?<content> [^;\\n]+ )){0,1} `, 'gnx');
No, `leafDirective` se usa a modo de singleton en: https://github.com/Leaflet/Leafdoc/blob/ca70b831529fade93bf80f54dfe1467d1ff086d8/src/leafdoc.js#L276

Y además, las llamadas a `redoLeafDirective` ignoran el valor de retorno: https://github.com/Leaflet/Leafdoc/blob/ca70b831529fade93bf80f54dfe1467d1ff086d8/src/leafdoc.js#L147

Me temo que el no asignar el valor va a hacer que eso falle; habría que ver alguna otra manera de hacer esto.

2020-07-21 23:49 UTC, mondeja commented on src/regexps.mjs
> -	leafDirective = xRegExp(`  \\s* ${  char  } (?<directive> \\S+ ) (\\s+ (?<content> [^;\\n]+ )){0,1} `, 'gnx');
Mira [el último commit](https://github.com/Leaflet/Leafdoc/pull/53/commits/dbbd9ac111f7eab80b9880dfbf4225435eb3ca3b), creo que está resuelto así.

2020-07-22 08:50 UTC, mondeja commented
It seems that the pull to `comment-patterns` have been merged to the master. So, when a new version of `multilang-extract-comments` have been released with  `.mjs` file detection support, I will change the version in `package.json` and remove the `.mjs` exception in `src/parsers/multilang.mjs`.

2020-07-24 09:26 UTC, mondeja commented
He actualizado la versión de `multilang-extract-comments` para soportar archivos `.mjs`.

2020-07-31 07:47 UTC, IvanSanchez approved these changes

2020-07-31 07:47 UTC, merged